#  it work!!!!
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvdocsify-helm
  namespace: helm-docsify
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/pwa/git/web/www"